import type React from 'react';
import type { ComparisonReport } from './compareTypes';
import type { RedactRegion } from './redactPdfUtils';
import type { SignaturePlacement } from './signPdfUtils';
import type { SignPdfEditorHandle } from './components/SignPdfEditor';
import type { HtmlInputMode } from './toolUploadConfig';
import type { usePdfEncryptionGate } from './usePdfEncryptionGate';
import type { SuiteTool } from './suiteCatalog';
import type { AppView } from './routing';
import type { CompressLevel } from './backendBridge';

export interface ToolPageBindings {
  goToView: (view: AppView, path: string, tool?: SuiteTool | null) => void;
  setComparisonReport: (report: ComparisonReport | null) => void;
  file: File | null;
  setFile: (file: File | null) => void;
  extraFiles: File[];
  setExtraFiles: (files: File[]) => void;
  compareFile2: File | null;
  setCompareFile2: (file: File | null) => void;
  toolText: string;
  setToolText: (value: string) => void;
  toolTitle: string;
  setToolTitle: (value: string) => void;
  htmlInputMode: HtmlInputMode;
  setHtmlInputMode: (mode: HtmlInputMode) => void;
  fileUploadFeedback: { msg: string; type: 'ok' | 'error' } | null;
  setFileUploadFeedback: (feedback: { msg: string; type: 'ok' | 'error' } | null) => void;
  onPrimaryPdfSelected: (file: File) => void;
  onPrimaryPdfInvalid: (msg: string) => void;
  pdfGate: ReturnType<typeof usePdfEncryptionGate>;
  encryptedPdfEntries: {
    name: string;
    password: string;
    onPasswordChange: (value: string) => void;
  }[];
  redactRegions: RedactRegion[];
  setRedactRegions: (regions: RedactRegion[]) => void;
  comparisonReport: ComparisonReport | null;
  isProcessing: boolean;
  handleExecuteTool: (toolId: string) => void;
  splitRange: string;
  setSplitRange: (value: string) => void;
  deletePageStr: string;
  setDeletePageStr: (value: string) => void;
  extractPageStr: string;
  setExtractPageStr: (value: string) => void;
  orderStr: string;
  setOrderStr: (value: string) => void;
  ocrLang: string;
  setOcrLang: (value: string) => void;
  rotationAngle: number;
  setRotationAngle: (value: number) => void;
  rotationScope: string;
  setRotationScope: (value: string) => void;
  pageNumFormat: string;
  setPageNumFormat: (value: string) => void;
  pageNumSize: number;
  setPageNumSize: (value: number) => void;
  pageNumAlign: string;
  setPageNumAlign: (value: string) => void;
  watermarkText: string;
  setWatermarkText: (value: string) => void;
  watermarkSize: number;
  setWatermarkSize: (value: number) => void;
  watermarkAngle: number;
  setWatermarkAngle: (value: number) => void;
  watermarkOpacity: number;
  setWatermarkOpacity: (value: number) => void;
  watermarkColor: string;
  setWatermarkColor: (value: string) => void;
  cropLeft: number;
  setCropLeft: (value: number) => void;
  cropRight: number;
  setCropRight: (value: number) => void;
  cropTop: number;
  setCropTop: (value: number) => void;
  cropBottom: number;
  setCropBottom: (value: number) => void;
  metadataTitle: string;
  setMetadataTitle: (value: string) => void;
  metadataAuthor: string;
  setMetadataAuthor: (value: string) => void;
  metadataSubject: string;
  setMetadataSubject: (value: string) => void;
  metadataCreator: string;
  setMetadataCreator: (value: string) => void;
  protectPass: string;
  setProtectPass: (value: string) => void;
  signEditorRef: React.RefObject<SignPdfEditorHandle | null>;
  sigPlacement: SignaturePlacement;
  setSigPlacement: (placement: SignaturePlacement) => void;
  signatureReady: boolean;
  setSignatureReady: (ready: boolean) => void;
  toolRunStatus: { msg: string; type: 'info' | 'ok' | 'error' } | null;
  setToolRunStatus: (status: { msg: string; type: 'info' | 'ok' | 'error' } | null) => void;
  addLog: (msg: string, type?: 'info' | 'success' | 'error') => void;
  compressLevel: CompressLevel;
  setCompressLevel: (level: CompressLevel) => void;
  compressHoverLevel: CompressLevel | null;
  setCompressHoverLevel: (level: CompressLevel | null) => void;
  compressRetainMetadata: boolean;
  setCompressRetainMetadata: (value: boolean) => void;
  compressTotalBytes: number;
  repairStrategy: string;
  setRepairStrategy: (value: string) => void;
  unlockPassword: string;
  setUnlockPassword: (value: string) => void;
  formsFlatten: boolean;
  setFormsFlatten: (value: boolean) => void;
  jpgDpi: string;
  setJpgDpi: (value: string) => void;
  pdfaStandard: string;
  setPdfaStandard: (value: string) => void;
}
